def test_results_content = ''
def gist_url = ''
pipeline {
  agent any
  environment {
    REPO_NAME = "NLPModelsKnitro.jl"
    OWNER = "ProofOfConceptForJuliSmoothOptimizers"
    PR_NUMBER = "${BRANCH_NAME.tokenize('PR-')[0]}"
  }
  stages {
    stage ('Testing Stage') {
      steps {
        sh """
          echo "allo!" > test_results.txt
        """
      }
    }
    stage ('Write Comment') {
      steps {
        sh """julia test/send_gist_url.jl"""
      }
    }
  }
  post {
    success {
      echo "SUCCESS!"  
    }
    cleanup {
      sh 'printenv'
      sh 'git reset --hard'
      sh 'git clean -fd'
    }
  }
}
